# Limpeza de crimes

In [5]:
## Importação das libs e do dataframe
## Fonte dos dados: http://dadosabertos.c3sl.ufpr.br/curitiba/Sigesguarda/

import pandas as pd

df = pd.read_csv('../dados/2021-07-01sigesguarda.csv', sep=';', encoding="latin-1", low_memory=False)
df = df.drop(0) # Tirar a primeira linha, que é ------
df.head()

,ATENDIMENTO_ANO,ATENDIMENTO_BAIRRO_NOME,EQUIPAMENTO_URBANO_NOME,FLAG_EQUIPAMENTO_URBANO,FLAG_FLAGRANTE,LOGRADOURO_NOME,NATUREZA1_DEFESA_CIVIL,NATUREZA1_DESCRICAO,NATUREZA2_DEFESA_CIVIL,NATUREZA2_DESCRICAO,...,OCORRENCIA_HORA,OCORRENCIA_MES,OPERACAO_DESCRICAO,ORIGEM_CHAMADO_DESCRICAO,REGIONAL_FATO_NOME,SECRETARIA_NOME,SECRETARIA_SIGLA,SERVICO_NOME,SITUACAO_EQUIPE_DESCRICAO,NUMERO_PROTOCOLO_156
1,2009,CIDADE INDUSTRIAL,NaN,NÃO,NÃO,DAVI XAVIER DA SILVA,0,Alarmes,NaN,NaN,...,15:14:00,1,NaN,"NÃO CADASTRAR ""ANTIGO SIGA""",CIC,FUNDAÇÃO DE AÇÃO SOCIAL,FAS,SIGA,NaN,NaN
2,2009,FAZENDINHA,BOSQUE DA FAZENDINHA,SIM,NÃO,CARLOS KLEMTZ,0,Roubo,NaN,NaN,...,15:22:00,1,NaN,153,PORTÃO,SECRETARIA MUNICIPAL MEIO AMBIENTE,SMMA,NORMAL,NaN,NaN
3,2009,UBERABA,NaN,NÃO,NÃO,DOUTOR JOÃO DE PAULA MOURA BRITO,0,Animais,NaN,NaN,...,15:59:00,1,NaN,156,CAJURU,SECRETARIA MUNICIPAL DA SAÚDE,SMS,SACAF,NaN,2640856
4,2009,SÍTIO CERCADO,NaN,NÃO,NÃO,EDGARD CAVALCANTI DE ALBUQUERQUE,0,Animais,NaN,NaN,...,16:13:00,1,NaN,156,BAIRRO NOVO,SECRETARIA MUNICIPAL DA SAÚDE,SMS,SACAF,NaN,2640854
5,2009,TATUQUARA,CENTRO DE ESPORTE E LAZER SANTA RITA,SIM,NÃO,CARLOS MUNHOZ DA ROCHA,0,Alarmes,NaN,NaN,...,16:29:00,1,NaN,"NÃO CADASTRAR ""ANTIGO SIGA""",PINHEIRINHO,FUNDAÇÃO DE AÇÃO SOCIAL,FAS,SIGA,NaN,NaN

In [3]:
df['ORIGEM_CHAMADO_DESCRICAO'].unique()

array(['NÃO CADASTRAR "ANTIGO SIGA"', '153', '156', 'IMEDIATA',
       'CCO URBS', 'CIOSP (190)', 'VAZIO "NÃO CADASTRAR" ANTIGO AOS GMS',
       'À VIATURA', '199', 'G5', 'CCO BARIGUI', 'FONE',
       'CCO RUAS DA CIDADANIA', 'OFÍCIO', 'AOS GMS', 'SAMU', 'SIGA',
       'CCO PUC', 'EMAIL', 'CCO SÍTIO CERCADO', 'CCO MUNICIPAL URBS',
       'REDE SOCIAL', 'TOTEM RUA SÃO FRANSICO',
       'CASA DA MULHER BRASILEIRA', 'CENTRAL DE FLAGRANTES', 'NRGM',
       'VEPPER', 'SETRAN', 'CCO MURALHA DIGITAL',
       'BOTÃO DO PÂNICO ESCOLAS',
       'BOTÃO DO PÂNICO PATRULHA MARIA DA PENHA'], dtype=object)

In [6]:
#df[df.isna().any(axis=1)]
# Filtrando apenas as colunas mais relevantes
df = df[['ATENDIMENTO_ANO', 'ATENDIMENTO_BAIRRO_NOME', 'EQUIPAMENTO_URBANO_NOME', 'LOGRADOURO_NOME', 'NATUREZA1_DESCRICAO', 'NATUREZA2_DESCRICAO','SUBCATEGORIA1_DESCRICAO', 'OCORRENCIA_ANO', 'OCORRENCIA_MES','OCORRENCIA_DATA','OCORRENCIA_HORA', 'OCORRENCIA_DIA_SEMANA','ORIGEM_CHAMADO_DESCRICAO', 'REGIONAL_FATO_NOME']]

In [3]:
df.columns

Index(['ATENDIMENTO_ANO', 'ATENDIMENTO_BAIRRO_NOME', 'EQUIPAMENTO_URBANO_NOME',
       'LOGRADOURO_NOME', 'NATUREZA1_DESCRICAO', 'NATUREZA2_DESCRICAO',
       'SUBCATEGORIA1_DESCRICAO', 'OCORRENCIA_ANO', 'OCORRENCIA_MES',
       'OCORRENCIA_DATA', 'OCORRENCIA_HORA', 'OCORRENCIA_DIA_SEMANA',
       'ORIGEM_CHAMADO_DESCRICAO', 'REGIONAL_FATO_NOME'],
      dtype='object')

In [7]:
# Replace em dados nulos
df['ATENDIMENTO_ANO'] = df['ATENDIMENTO_ANO'].fillna(0)
df['ATENDIMENTO_BAIRRO_NOME'] = df['ATENDIMENTO_BAIRRO_NOME'].fillna("NÃO INFORMADO")
df['EQUIPAMENTO_URBANO_NOME'] = df['EQUIPAMENTO_URBANO_NOME'].fillna("NÃO INFORMADO")
df['LOGRADOURO_NOME'] = df['LOGRADOURO_NOME'].fillna("NÃO INFORMADO")
df['NATUREZA1_DESCRICAO'] = df['NATUREZA1_DESCRICAO'].fillna("NÃO INFORMADO")
df['NATUREZA2_DESCRICAO'] = df['NATUREZA2_DESCRICAO'].fillna("NÃO INFORMADO")
df['SUBCATEGORIA1_DESCRICAO'] = df['SUBCATEGORIA1_DESCRICAO'].fillna("NÃO INFORMADO")
df['OCORRENCIA_DIA_SEMANA'] = df['OCORRENCIA_DIA_SEMANA'].fillna("NÃO INFORMADO")
df['ORIGEM_CHAMADO_DESCRICAO'] = df['ORIGEM_CHAMADO_DESCRICAO'].fillna("NÃO INFORMADO")
df['REGIONAL_FATO_NOME'] = df['REGIONAL_FATO_NOME'].fillna("NÃO INFORMADO")

# Convertendo as colunas para o tipo certo
df['ATENDIMENTO_ANO'] = df['ATENDIMENTO_ANO'].astype(int)
df['OCORRENCIA_ANO'] = df['OCORRENCIA_ANO'].astype(int)
df['OCORRENCIA_MES'] = df['OCORRENCIA_MES'].astype(int)
df['OCORRENCIA_DATA'] = pd.to_datetime(df['OCORRENCIA_DATA'])
df['OCORRENCIA_HORA'] = pd.to_datetime(df['OCORRENCIA_HORA'])

df['QTDE'] = 1

df[df.isna().any(axis=1)]
#df = df.astype({'ATENDIMENTO_ANO': int, 'OCORRENCIA_ANO':int, 'OCORRENCIA_MES':int})

Empty DataFrame
Columns: [ATENDIMENTO_ANO, ATENDIMENTO_BAIRRO_NOME, EQUIPAMENTO_URBANO_NOME, LOGRADOURO_NOME, NATUREZA1_DESCRICAO, NATUREZA2_DESCRICAO, SUBCATEGORIA1_DESCRICAO, OCORRENCIA_ANO, OCORRENCIA_MES, OCORRENCIA_DATA, OCORRENCIA_HORA, OCORRENCIA_DIA_SEMANA, ORIGEM_CHAMADO_DESCRICAO, REGIONAL_FATO_NOME, QTDE]
Index: []

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354335 entries, 1 to 354335
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ATENDIMENTO_ANO           354335 non-null  int64
 1   ATENDIMENTO_BAIRRO_NOME   354335 non-null  object
 2   EQUIPAMENTO_URBANO_NOME   354335 non-null  object
 3   LOGRADOURO_NOME           354335 non-null  object
 4   NATUREZA1_DESCRICAO       354335 non-null  object
 5   NATUREZA2_DESCRICAO       354335 non-null  object
 6   SUBCATEGORIA1_DESCRICAO   354335 non-null  object
 7   OCORRENCIA_ANO            354335 non-null  int64
 8   OCORRENCIA_MES            354335 non-null  int64
 9   OCORRENCIA_DATA           354335 non-null  datetime64[ns]
 10  OCORRENCIA_HORA           354335 non-null  datetime64[ns]
 11  OCORRENCIA_DIA_SEMANA     354335 non-null  object
 12  ORIGEM_CHAMADO_DESCRICAO  354335 non-null  object
 13  REGIONAL_FATO_NOME        354335 non-null  object
 14  QTDE                      354335 non-null  int64
dtypes: datetime64[ns](2), int64(4), object(9)
memory usage: 43.3+ MB

In [8]:
#Renomear as colunas
df = df.rename(columns={'ATENDIMENTO_BAIRRO_NOME': 'BAIRRO', 'EQUIPAMENTO_URBANO_NOME': 'LOCAL_PUBLICO', 'LOGRADOURO_NOME': 'RUA',\
                       'NATUREZA1_DESCRICAO': 'DESCRICAO1', 'NATUREZA2_DESCRICAO':'DESCRICAO2',\
                        'SUBCATEGORIA1_DESCRICAO': 'SUBCATEGORIA', 'REGIONAL_FATO_NOME': 'REGIONAL'
                       })

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354335 entries, 1 to 354335
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ATENDIMENTO_ANO           354335 non-null  int64
 1   BAIRRO                    354335 non-null  object
 2   LOCAL_PUBLICO             354335 non-null  object
 3   RUA                       354335 non-null  object
 4   DESCRICAO1                354335 non-null  object
 5   DESCRICAO2                354335 non-null  object
 6   SUBCATEGORIA              354335 non-null  object
 7   OCORRENCIA_ANO            354335 non-null  int64
 8   OCORRENCIA_MES            354335 non-null  int64
 9   OCORRENCIA_DATA           354335 non-null  datetime64[ns]
 10  OCORRENCIA_HORA           354335 non-null  datetime64[ns]
 11  OCORRENCIA_DIA_SEMANA     354335 non-null  object
 12  ORIGEM_CHAMADO_DESCRICAO  354335 non-null  object
 13  REGIONAL                  354335 non-null  object
 14  QTDE                      354335 non-null  int64
dtypes: datetime64[ns](2), int64(4), object(9)
memory usage: 43.3+ MB

In [7]:
df.head()

,ATENDIMENTO_ANO,BAIRRO,LOCAL_PUBLICO,RUA,DESCRICAO1,DESCRICAO2,SUBCATEGORIA,OCORRENCIA_ANO,OCORRENCIA_MES,OCORRENCIA_DATA,OCORRENCIA_HORA,OCORRENCIA_DIA_SEMANA,ORIGEM_CHAMADO_DESCRICAO,REGIONAL,QTDE
1,2009,CIDADE INDUSTRIAL,NÃO INFORMADO,DAVI XAVIER DA SILVA,Alarmes,NÃO INFORMADO,Disparo de Alarme (violação),2009,1,2009-01-01 15:14:00,2021-06-20 15:14:00,QUINTA,"NÃO CADASTRAR ""ANTIGO SIGA""",CIC,1
2,2009,FAZENDINHA,BOSQUE DA FAZENDINHA,CARLOS KLEMTZ,Roubo,NÃO INFORMADO,Transeunte,2009,1,2009-01-01 15:22:00,2021-06-20 15:22:00,QUINTA,153,PORTÃO,1
3,2009,UBERABA,NÃO INFORMADO,DOUTOR JOÃO DE PAULA MOURA BRITO,Animais,NÃO INFORMADO,Cão solto em via pública,2009,1,2009-01-01 15:59:00,2021-06-20 15:59:00,QUINTA,156,CAJURU,1
4,2009,SÍTIO CERCADO,NÃO INFORMADO,EDGARD CAVALCANTI DE ALBUQUERQUE,Animais,NÃO INFORMADO,Cão solto em via pública,2009,1,2009-01-01 16:13:00,2021-06-20 16:13:00,QUINTA,156,BAIRRO NOVO,1
5,2009,TATUQUARA,CENTRO DE ESPORTE E LAZER SANTA RITA,CARLOS MUNHOZ DA ROCHA,Alarmes,NÃO INFORMADO,Disparo de Alarme (violação),2009,1,2009-01-01 16:29:00,2021-06-20 16:29:00,QUINTA,"NÃO CADASTRAR ""ANTIGO SIGA""",PINHEIRINHO,1

In [9]:
df = df[df.OCORRENCIA_ANO >= 2015]
df.head()

,ATENDIMENTO_ANO,BAIRRO,LOCAL_PUBLICO,RUA,DESCRICAO1,DESCRICAO2,SUBCATEGORIA,OCORRENCIA_ANO,OCORRENCIA_MES,OCORRENCIA_DATA,OCORRENCIA_HORA,OCORRENCIA_DIA_SEMANA,ORIGEM_CHAMADO_DESCRICAO,REGIONAL,QTDE
138468,2015,ABRANCHES,NÃO INFORMADO,CARMELINA CAVASSIN,Disparo de arma,NÃO INFORMADO,Disparo de arma por GM com munição letal,2015,1,2015-01-01 00:26:00,2021-08-24 00:26:00,QUINTA,153,BOA VISTA,1
138469,2015,ALTO DA RUA XV,NÃO INFORMADO,CAMÕES,Animais,NÃO INFORMADO,Cão solto em via pública,2015,1,2015-01-01 00:45:00,2021-08-24 00:45:00,QUINTA,153,MATRIZ,1
138470,2015,PRADO VELHO,NÃO INFORMADO,GUABIROTUBA,Apoio,NÃO INFORMADO,Apoio à PMPR,2015,1,2015-01-01 00:56:00,2021-08-24 00:56:00,QUINTA,153,MATRIZ,1
138471,2015,CAMPINA DO SIQUEIRA,TERMINAL CAMPINA DO SIQUEIRA,PADRE ANCHIETA,Explosão,NÃO INFORMADO,NÃO INFORMADO,2015,1,2015-01-01 01:08:00,2021-08-24 01:08:00,QUINTA,153,SANTA FELICIDADE,1
138472,2015,XAXIM,ESTAÇÃO TUBO SÃO PEDRO,BR CENTO E DEZESSEIS,Roubo,NÃO INFORMADO,Transporte Coletivo,2015,1,2015-01-01 00:01:00,2021-08-24 00:01:00,QUINTA,153,BOQUEIRÃO,1

In [8]:
pwd

'/home/patriky/Documentos/TCC/src'

In [9]:
# Salvar dataframe de abril em um arquivo separado

df.to_csv("../dados/dados_limpos/base_limpa_junho_2021.csv", index=False, encoding="latin-1")